language: python

matrix:
  include:

    # Here you can add or remove specific builds, and Python versions. You
    # should currently be able to use Python 2.6, 2.7, or 3.3 or later.

    - stage: 'style checks'
      python: '2.7.15'
      language: python
      env: TEST_SUITE=flake8
    - stage: 'unit tests'
      python: 2.7.15
      env: TEST_SUITE=unit

stages:
  - 'style checks'
  - 'unit tests'

before_install:

  # Here we just install Miniconda, which you shouldn't have to change.

  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - chmod +x miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda info -a

install:

  # We just set up a conda environment with the right Python version. This
  # should not need changing.

  - conda env create -f conda-python-$TRAVIS_PYTHON_VERSION-test-env.yaml -n test
  - source activate test
  - conda install -q --yes flake8

script:
  - bash .travis-$TEST_SUITE-script.sh
