name: ci-py38
channels:
  - https://root.cern/download/conda-nightly/latest
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - flake8
  - pytest
  - numpy
  - openjdk=11
  - pyspark=3
  - root=6.23
