name: ci-py37
channels:
  - conda-forge
  - defaults
dependencies:
  - pyspark
  - flake8
  - pytest
  - yapf
  - sphinx
  - sphinx_rtd_theme
  - pandas
  - numpy
  - jupyter
  - matplotlib
  - openjdk=8
  - python=3.7
  - root=6.20
